# Generated by Django 6.1 on 2026-09-13 13:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/avatar_pnrczr.png', upload_to=base.models.User.upload_dir),
        ),
    ]
